name: Flowdesk Local
values:
  - key: base_url
    value: 'http://localhost:8000'
    enabled: true
    type: default
  - key: token
    value: ''
    enabled: true
    type: default
  - key: invite_token
    value: ''
    enabled: true
    type: default
  - key: reset_token
    value: ''
    enabled: true
    type: default
