"""Response hardening around the complete ASGI stack, including server errors."""

import base64
import hashlib
from html.parser import HTMLParser

from fastapi import FastAPI
from starlette._utils import get_route_path
from starlette.datastructures import MutableHeaders
from starlette.middleware.cors import CORSMiddleware
from starlette.middleware.httpsredirect import HTTPSRedirectMiddleware
from starlette.middleware.trustedhost import TrustedHostMiddleware

from app.core import config

API_CSP = "default-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'"
SECURITY_HEADERS = {
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Content-Security-Policy": API_CSP,
    "Cache-Control": "no-store",
    "Cross-Origin-Resource-Policy": "same-origin",
}


class _InlineScripts(HTMLParser):
    """Hash the exact inline scripts generated by FastAPI's documentation UI."""

    def __init__(self):
        super().__init__(convert_charrefs=False)
        self.scripts = []
        self.current = None

    def handle_starttag(self, tag, attrs):
        if tag == "script" and not dict(attrs).get("src"):
            self.current = []

    def handle_data(self, data):
        if self.current is not None:
            self.current.append(data)

    def handle_endtag(self, tag):
        if tag == "script" and self.current is not None:
            digest = hashlib.sha256("".join(self.current).encode()).digest()
            self.scripts.append("'sha256-" + base64.b64encode(digest).decode() + "'")
            self.current = None


def documentation_csp(body: bytes) -> str:
    parser = _InlineScripts()
    parser.feed(body.decode("utf-8"))
    scripts = " ".join(parser.scripts)
    # Swagger/ReDoc load assets from these CDNs. Inline styles are needed by
    # their UI libraries; inline scripts only execute with an exact body hash.
    return (
        "default-src 'none'; base-uri 'none'; frame-ancestors 'none'; "
        "form-action 'none'; "
        f"script-src 'self' https://cdn.jsdelivr.net {scripts}; "
        "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com; "
        "font-src 'self' https://fonts.gstatic.com; "
        "img-src 'self' data: https://fastapi.tiangolo.com; "
        "connect-src 'self'; worker-src 'self' blob:"
    )


class SecurityHeadersMiddleware:
    def __init__(self, app, *, docs_paths, force_https, hsts_max_age):
        self.app = app
        self.docs_paths = docs_paths
        self.force_https = force_https
        self.hsts_value = f"max-age={hsts_max_age}; includeSubDomains"

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            return await self.app(scope, receive, send)
        start = None
        chunks = []

        async def hardened_send(message):
            nonlocal start
            if message["type"] == "http.response.start":
                headers = MutableHeaders(scope=message)
                for header, value in SECURITY_HEADERS.items():
                    headers[header] = value
                if self.force_https and scope.get("scheme") == "https":
                    headers["Strict-Transport-Security"] = self.hsts_value
                # Only buffer the small generated HTML docs. API downloads and
                # streaming responses pass through unchanged, without buffering.
                if (get_route_path(scope) in self.docs_paths
                        and message["status"] == 200
                        and headers.get("content-type", "").startswith("text/html")):
                    start = message
                    return
            elif message["type"] == "http.response.body" and start is not None:
                chunks.append(message.get("body", b""))
                if message.get("more_body", False):
                    return
                body = b"".join(chunks)
                MutableHeaders(scope=start)["Content-Security-Policy"] = documentation_csp(body)
                await send(start)
                start = None
                await send({"type": "http.response.body", "body": body})
                return
            await send(message)

        await self.app(scope, receive, hardened_send)


class SecureFastAPI(FastAPI):
    def build_middleware_stack(self):
        # add_middleware lives inside ServerErrorMiddleware. Wrapping the built
        # stack also protects generic 500s, CORS preflights and host rejections.
        return SecurityHeadersMiddleware(
            CORSMiddleware(
                super().build_middleware_stack(),
                allow_origins=config.CORS_ORIGINS,
                allow_credentials=True,
                allow_methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
                allow_headers=["Authorization", "Content-Type"],
            ),
            docs_paths={self.docs_url, self.redoc_url, self.swagger_ui_oauth2_redirect_url},
            force_https=config.FORCE_HTTPS,
            hsts_max_age=config.HSTS_MAX_AGE,
        )


def configure_transport_security(app: FastAPI) -> None:
    # Last added runs first: reject an unknown Host before redirecting to it.
    if config.FORCE_HTTPS:
        app.add_middleware(HTTPSRedirectMiddleware)
    if config.ALLOWED_HOSTS:
        app.add_middleware(TrustedHostMiddleware, allowed_hosts=config.ALLOWED_HOSTS)
